package cmodule.shine;

extern class FSM_update_compress extends Machine {
	var f0 : Float;
	var f1 : Float;
	var f2 : Float;
	var f3 : Float;
	var f4 : Float;
	var f5 : Float;
	var f6 : Float;
	var i0 : Int;
	var i1 : Int;
	var i10 : Int;
	var i11 : Int;
	var i12 : Int;
	var i13 : Int;
	var i14 : Int;
	var i15 : Int;
	var i16 : Int;
	var i17 : Int;
	var i18 : Int;
	var i19 : Int;
	var i2 : Int;
	var i20 : Int;
	var i21 : Int;
	var i22 : Int;
	var i23 : Int;
	var i24 : Int;
	var i25 : Int;
	var i26 : Int;
	var i27 : Int;
	var i28 : Int;
	var i29 : Int;
	var i3 : Int;
	var i30 : Int;
	var i31 : Int;
	var i4 : Int;
	var i5 : Int;
	var i6 : Int;
	var i7 : Int;
	var i8 : Int;
	var i9 : Int;
	function new() : Void;
	static var NumberRegCount : Int;
	static var intRegCount : Int;
	static function start() : Void;
}
